### ISSUE TITLE
Big to-do list for 1.0

### ISSUE THREAD

**Issue by mdcfe** [md678685/justcord-3#1]
- [x] Custom formatting (both ways) - 95419442d3a104b40a9b74068110d73ac49f93e8
- [x] Player join/leave messages on Discord - 856df08ef3e1d4eaf00d349f943c42d6e6233dde
- [x] Show death messages in Discord - bb7cb14f0b4d3e66785c13a5ff2db387aec0038a
- [x] Channel topic/description updating - 1a1910e4ac1998d281b341926e5a5c995ff74c55
- [x] Game status updating - 50a2ced1435bc43caa6f4d5cb101045672037756
- [x] Config reloading and defaults - 789e1a2e8604d200245efebf6b86f71f92cc32e9 
- [x] Catch errors in templates (#3, #4) - e245d9ece5908fa4561a3077a3604d752c8c3092
- [ ] Discord-to-player linking for use with other packages
- [x] Different colour or prefix in JC3 chat for Discord messages - f4a2e9cd187df2ff1953f768375676027463bed1
- [ ] Fully document config (#5)
